notebooks:

				tools/nb_to_doc.py plot
				tools/nb_to_doc.py analyze
				tools/nb_to_doc.py normalize
				tools/nb_to_doc.py reduce
				tools/nb_to_doc.py align
				tools/nb_to_doc.py cluster
				tools/nb_to_doc.py geo
				tools/nb_to_doc.py text
