# -*- coding: utf-8 -*-
#
# hypertools documentation build configuration file, created by
# sphinx-quickstart on Thu Feb  2 08:22:16 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
import sys, os

# plotly scraper for sphinx-gallery: renders plotly figures produced by
# gallery examples (requires kaleido). Falls back gracefully if plotly is
# unavailable so the docs still build.
try:
    import plotly.io as pio
    pio.renderers.default = 'sphinx_gallery_png'
    from plotly.io._sg_scraper import plotly_sg_scraper
except Exception:  # pragma: no cover
    def plotly_sg_scraper(*args, **kwargs):
        return ''
sys.path.insert(0, os.path.abspath('../'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'numpydoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.viewcode',
    'sphinx_gallery.gen_gallery',
    # renders the .. video:: directives sphinx-gallery emits for
    # matplotlib animations (matplotlib_animations = (True, 'mp4'))
    'sphinxcontrib.video',
    'nbsphinx']

# allow nbsphinx errors for missing optional dependencies
nbsphinx_allow_errors = True

# Never execute notebooks during the docs build: tutorial notebooks are
# committed pre-executed (with outputs), and 'auto' also re-executed every
# sphinx-gallery-generated .ipynb -- doubling build time and hanging on
# plotly/kaleido exports inside the nbsphinx kernel.
nbsphinx_execute = 'never'

# Generate the API documentation when building
autosummary_generate = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'hypertools'
copyright = u'2017, Contextual Dynamics Laboratory'
author = u'Andrew C. Heusser, Kirsten Ziman, Lucy L. W. Owen, Jeremy R. Manning'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# Import version from package
import hypertools
# The short X.Y version.
version = hypertools.__version__
# The full version, including alpha/beta/rc tags.
release = hypertools.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store',
                    # sphinx-gallery writes a downloadable .ipynb next to
                    # each generated .rst; without this exclusion nbsphinx
                    # claims the page and renders the UNEXECUTED notebook
                    # (code cells, no output, no animations) instead of
                    # the gallery page
                    'auto_examples/*.ipynb']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# # -- Options for HTML output ----------------------------------------------
#
# # The theme to use for HTML and HTML Help pages.  See the documentation for
# # a list of builtin themes.
# #
# html_theme = 'bootstrap'
#
# # Theme options are theme-specific and customize the look and feel of a theme
# # further.  For a list of options available for each theme, see the
# # documentation.
# #
# # html_theme_options = {}
#
# # Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add custom CSS and JS
html_css_files = [
    'custom.css',
]

html_js_files = [
    'gallery-fixes.js',
]

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages: Furo with the ContextLab
# look (ported from https://github.com/ContextLab/scheduler, which is based
# on the lab's website) -- Nunito Sans, lowercase thin headings, and the
# lab's green as the brand color. The font/typography rules live in
# _static/custom.css.
html_theme = 'furo'

extlinks = {'github': 'https://github.com/ContextLab/hypertools'}

html_title = 'hypertools'

html_theme_options = {
    'source_repository': 'https://github.com/ContextLab/hypertools',
    'source_branch': 'master',
    'source_directory': 'docs/',
    'light_css_variables': {
        'color-brand-primary': '#007030',
        'color-brand-content': '#007030',
        'font-stack': "'Nunito Sans', -apple-system, BlinkMacSystemFont, "
                      "'Segoe UI', Helvetica, Arial, sans-serif",
    },
    'dark_css_variables': {
        'color-brand-primary': '#4CAF50',
        'color-brand-content': '#4CAF50',
    },
    'footer_icons': [
        {
            'name': 'GitHub',
            'url': 'https://github.com/ContextLab/hypertools',
            'html': '<svg stroke="currentColor" fill="currentColor" '
                    'stroke-width="0" viewBox="0 0 16 16"><path '
                    'fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 '
                    '2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 '
                    '0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-'
                    '.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 '
                    '1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.'
                    '51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-'
                    '2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 '
                    '1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 '
                    '2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 '
                    '3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-'
                    '.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 '
                    '16 8c0-4.42-3.58-8-8-8z"></path></svg>',
            'class': '',
        },
    ],
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'hypertoolsdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'hypertools.tex', u'hypertools Documentation',
     u'Contextual Dynamics Laboratory', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'hypertools', u'hypertools Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'hypertools', u'hypertools Documentation',
     author, 'hypertools', 'One line description of project.',
     'Miscellaneous'),
]

sphinx_gallery_conf = {
    # path to your examples scripts
    'examples_dirs' : '../examples',
    # path where to save gallery generated examples
    'gallery_dirs'  : 'auto_examples',
    # Abort on first failure
    'abort_on_example_error': False,
    # Execute code to generate plots
    'plot_gallery': True,
    # execute EVERY example (the sphinx-gallery default only executes
    # files named plot_*, which left animate*/chemtrails/precog/explore/
    # save_*/analyze pages with code but no rendered output)
    'filename_pattern': r'.*\.py',
    # render matplotlib FuncAnimations (exposed as variables in the
    # examples) as embedded HTML5 video via ffmpeg
    'matplotlib_animations': (True, 'mp4'),
    # Download all examples as zip files
    'download_all_examples': True,
    # Ignore warnings during gallery building
    'ignore_pattern': r'.*\.pyc$|.*\.pyo$|.*\.DS_Store$',
    # Expected failing examples - should be empty now with fixes
    'expected_failing_examples': [],
    # Performance optimizations
    'capture_repr': ('_repr_html_',),
    # scrape BOTH matplotlib figures and plotly figures (the plotly scraper
    # renders interactive figures into the gallery via kaleido)
    'image_scrapers': ('matplotlib', plotly_sg_scraper),
    # Limit memory usage display
    'show_memory': False,
    # Ensure proper thumbnail linking
    'first_notebook_cell': '%matplotlib inline',
    'thumbnail_size': (200, 200),
    # Enable references to work - for local docs, use relative path
    'reference_url': {
        'hypertools': None,  # Use relative links for local docs
        'matplotlib': 'https://matplotlib.org/stable/',
        'numpy': 'https://numpy.org/doc/stable/',
        'scipy': 'https://docs.scipy.org/doc/scipy/reference/',
        'pandas': 'https://pandas.pydata.org/pandas-docs/stable/',
        'scikit-learn': 'https://scikit-learn.org/stable/',
    }
}
